# Generated by Django 5.1.6 on 2025-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_management_app', '0002_alter_loan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default='No description provided', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_number',
            field=models.CharField(default='invalid', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('loan_repayment', 'Loan Repayment'), ('share_purchase', 'Share Purchase'), ('insurance_payment', 'Insurance Payment'), ('dividend_payment', 'Dividend Payment')], default='deposit', max_length=20),
        ),
    ]
