# Generated by Django 5.1.6 on 2025-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_management_app', '0003_rename_transaction_date_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='member',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(default='00000000', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('loan', 'Loan'), ('loan_repayment', 'Loan Repayment'), ('share_purchase', 'Share Purchase'), ('insurance_payment', 'Insurance Payment'), ('dividend_payment', 'Dividend Payment')], default='deposit', max_length=20),
        ),
    ]
