# Generated by Django 5.1.6 on 2025-03-13 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco_management_app', '0006_deposit_withdraw_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deposit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_management_app.member'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco_management_app.member'),
        ),
    ]
